# Use the Alpine-based Node.js image for a smaller footprint
FROM node:23-alpine3.20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of your application code into the container
COPY . .

# Expose port 4000
EXPOSE 4000

# Start the app
CMD ["npm", "run", "start"]